In [1]:
import pandas as pd
import requests
import io

In [2]:
# Downloading the csv file from your GitHub account

url = "https://raw.githubusercontent.com/kelliwolf17/Final_Project/main/Resources/merged_df.csv" # Make sure the url is the raw version of the file on GitHub
download = requests.get(url).content

# Reading the downloaded content and turning it into a pandas dataframe
#data=pd.read_csv("File_path", sep='\t')

df = pd.read_csv(io.StringIO(download.decode('utf-8')), low_memory=False)

# Printing out the first 5 rows of the dataframe

df.head()

,ID,Year,LocationAbbr,Topic,Response,Data_Value_Type,Data_Value,Data_Value_Footnote_Symbol,Data_Value_Footnote,Low_Confidence_Limit,High_Confidence_Limit,Sample_Size,Stratification,StratificationType,IndicatorId,LocationOrder,ParentStateDisplayOrder
0,881138.0,2003.0,US,Age,18-24 years,Crude Prevalence,13.4,**,Median value reported with no confidence inter...,NaN,NaN,54.0,Overall,Overall,AGE,1.0,1.0
1,881139.0,2003.0,US,Age,25-34 years,Crude Prevalence,17.3,**,Median value reported with no confidence inter...,NaN,NaN,54.0,Overall,Overall,AGE,1.0,1.0
2,881140.0,2003.0,US,Age,35-44 years,Crude Prevalence,20.0,**,Median value reported with no confidence inter...,NaN,NaN,54.0,Overall,Overall,AGE,1.0,1.0
3,881141.0,2003.0,US,Age,45-54 years,Crude Prevalence,18.9,**,Median value reported with no confidence inter...,NaN,NaN,54.0,Overall,Overall,AGE,1.0,1.0
4,881142.0,2003.0,US,Age,55-64 years,Crude Prevalence,13.2,**,Median value reported with no confidence inter...,NaN,NaN,54.0,Overall,Overall,AGE,1.0,1.0

In [3]:
df.columns

Index(['ID', 'Year', 'LocationAbbr', 'Topic', 'Response', 'Data_Value_Type',
       'Data_Value', 'Data_Value_Footnote_Symbol', 'Data_Value_Footnote',
       'Low_Confidence_Limit', 'High_Confidence_Limit', 'Sample_Size',
       'Stratification', 'StratificationType', 'IndicatorId', 'LocationOrder',
       'ParentStateDisplayOrder'],
      dtype='object')

In [4]:
df.dtypes

ID                            float64
Year                          float64
LocationAbbr                   object
Topic                          object
Response                       object
Data_Value_Type                object
Data_Value                     object
Data_Value_Footnote_Symbol     object
Data_Value_Footnote            object
Low_Confidence_Limit          float64
High_Confidence_Limit         float64
Sample_Size                   float64
Stratification                 object
StratificationType             object
IndicatorId                    object
LocationOrder                 float64
ParentStateDisplayOrder       float64
dtype: object

In [5]:
# investigate Data_Value & change to float64
df.Data_Value.unique()

array(['13.4', '17.3', '20.0', '18.9', '13.2', '17.1', '13.3', '17.2',
       '19.9', '13.5', '19.3', '18.6', '17.9', '14.0', '18.4', '23.4',
       '23.2', '11.7', '9.3', '12.7', '19.2', '19.6', '12.8', '17.0',
       '18.8', '17.8', '13.7', '21.5', '18.5', '11.9', '14.9', '13.1',
       '21.6', '20.4', '12.3', '10.0', '16.7', '21.4', '19.7', '13.6',
       '16.9', '20.6', '17.6', '14.5', '21.7', '19.1', '12.0', '15.7',
       '11.1', '15.6', '17.4', '13.8', '21.9', '18.7', '12.4', '18.3',
       '15.3', '17.7', '15.9', '20.5', '14.2', '12.9', '12.6', '14.4',
       '19.5', '12.2', '18.2', '17.5', '15.0', '19.8', '16.3', '11.6',
       '20.2', '14.1', '10.7', '22.6', '15.1', '12.1', '21.2', '16.0',
       '16.6', '15.4', '14.8', '20.9', '13.9', '14.3', '16.8', '11.5',
       '22.1', '10.9', '19.4', '20.8', '13.0', '16.4', '15.8', '18.1',
       '19.0', '20.1', '16.1', '20.3', '14.6', '11.8', '23.1', '16.5',
       '10.3', '21.0', '16.2', '23.6', '23.3', '11.3', '8.4', nan, '12.5',
       '24.3', '8.5', '21.1', '21.3', '20.7', '22.7', '11.0', '14.7',
       '10.5', '22.2', '15.2', '10.6', '22.0', '15.5', '18.0', '9.4',
       '10.8', '22.4', '11.2', '24.4', '23.0', '9.6', '23.7', '9.9',
       '23.8', '8.8', '6.6', '26.9', '7.7', '27.3', '9.1', '25.4', '26.3',
       '26.2', '6.2', '26.0', '8.6', '25.7', '24.7', '10.4', '21.8',
       '27.8', '10.2', '6.4', '26.4', '9.5', '8.0', '29.2', '6.5', '24.2',
       '22.3', '7.9', '8.2', '7.4', '9.0', '6.1', '25.8', '11.4', '7.1',
       '22.9', '24.0', '6.3', '29.4', '25.9', '22.8', '5.1', '29.6',
       '5.0', '28.3', '7.8', '23.9', '6.8', '9.7', '25.5', '24.9', '22.5',
       '27.4', '23.5', '27.1', '24.1', '28.2', '25.1', '25.6', '26.1',
       '25.3', '25.0', '24.6', '24.5', '10.1', '25.2', '8.1', '9.8',
       '27.2', '36.2', '35.9', '36.0', '31.6', '36.6', '31.8', '37.9',
       '36.7', '38.3', '35.8', '31.5', '35.1', '33.4', '38.7', '44.3',
       '38.0', '41.0', '27.6', '36.1', '36.3', '48.2', '26.5', '36.9',
       '27.7', '37.6', '34.7', '34.9', '42.2', '37.1', '35.5', '30.0',
       '35.2', '34.8', '28.5', '32.8', '28.8', '35.4', '32.4', '32.9',
       '33.9', '33.7', '37.8', '26.8', '35.7', '42.5', '30.3', '35.3',
       '34.4', '36.8', '29.7', '30.6', '35.0', '38.4', '28.1', '37.0',
       '36.5', '37.2', '38.1', '38.2', '35.6', '39.9', '30.1', '34.6',
       '28.4', '33.8', '29.8', '33.3', '32.0', '32.6', '39.3', '34.2',
       '31.0', '29.5', '37.3', '33.2', '34.0', '42.0', '41.8', '39.4',
       '37.5', '31.7', '32.5', '36.4', '34.3', '38.9', '27.5', '37.7',
       '33.0', '40.7', '34.1', '39.7', '30.9', '42.4', '28.7', '43.7',
       '30.4', '42.8', '34.5', '30.2', '33.5', '29.1', '27.9', '31.2',
       '31.4', '37.4', '39.8', '24.8', '38.5', '28.6', '31.3', '39.1',
       '32.2', '42.3', '41.6', '32.1', '1.8', '2.0', '1.4', '2.6', '2.3',
       '2.1', '2.2', '1.9', '1.7', '45.4', '26.6', '28.0', '2.8', '30.8',
       '29.0', '1.5', '1.6', '38.8', '33.6', '31.1', '26.7', '1.3',
       '38.6', '1.2', '2.5', '31.9', '0.9', '46.0', '41.2', '2.7', '29.9',
       '39.2', '29.3', '32.7', '40.4', '2.9', '28.9', '30.5', '1.1',
       '2.4', '43.0', '3.2', '33.1', '40.1', '27.0', '40.5', '30.7',
       '43.1', '39.5', '32.3', '3.1', '1.0', '43.5', '40.8', '*', '44.4',
       '3.3', '39.0', '40.9', '41.1', '44.0', '40.6', '48.3', '44.9',
       '47.9', '44.2', '48.6', '41.4', '40.0', '40.2', '41.3', '45.6',
       '43.2', '42.9', '39.6', '45.2', '7.2', '0.7', '92.0', '92.1',
       '8.7', '90.3', '93.3', '92.6', '0.5', '91.7', '4.7', '0.6', '94.7',
       '5.9', '93.0', '91.6', '91.2', '0.8', '90.7', '91.5', '7.6',
       '93.1', '7.3', '6.7', '92.7', '6.0', '90.9', '91.9', '7.0', '92.9',
       '91.4', '5.5', '93.7', '0.4', '88.6', '6.9', '93.8', '5.6', '93.5',
       '5.7', '91.0', '93.2', '8.9', '90.2', '92.8', '92.5', '89.7',
       '92.2', '89.8', '5.8', '93.6', '89.5', '88.4', '88.8', '91.1',
       '89.9', '4.2', '90.5', '90.6', '4.3', '94.0', '8.3', '90.0',
       '90.4', '92.4', '7.5', '88.5', '91.8', '90.1', '5.3', '87.5',
       '0.2', '87.4', '87.3', '4.4', '4.8', '93.4', '89.4', '88.9', '9.2',
       '89.0', '91.3', '92.3', '89.6', '87.9', '0.1', '84.8', '86.7',
       '89.3', '90.8', '88.1', '89.1', '86.9', '86.0', '86.2', '87.0',
       '88.7', '87.7', '88.3', '87.6', '86.6', '85.7', '88.2', '88.0',
       '86.3', '89.2', '86.1', '85.4', '87.8', '86.4', '85.5', '0.3',
       '85.9', '85.6', '86.8', '5.2', '83.1', '87.1', '85.1', '87.2',
       '3.9', '84.0', '83.7', '84.5', '86.5', '3.7', '82.4', '85.0',
       '84.4', '81.3', '83.8', '4.6', '3.5', '83.6', '85.3', '85.2',
       '77.4', '84.2', '3.8', '81.0', '82.2', '84.9', '85.8', '83.4',
       '84.7', '83.2', '82.1', '82.7', '83.3', '80.5', '4.0', '4.9',
       '84.3', '83.9', '82.8', '81.2', '3.6', '81.9', '79.8', '84.6',
       '80.9', '82.5', '3.0', '3.4', '81.4', '78.6', '95.7', '94.3',
       '93.9', '94.5', '94.6', '95.0', '94.2', '5.4', '94.4', '4.5',
       '94.8', '47.8', '47.2', '44.7', '43.4', '51.1', '50.6', '54.5',
       '43.9', '46.6', '46.2', '55.2', '43.3', '43.6', '47.6', '62.2',
       '4.1', '46.3', '59.2', '50.2', '41.9', '49.1', '51.6', '52.4',
       '53.0', '54.7', '46.7', '45.3', '76.9', '77.3', '70.1', '80.8',
       '78.8', '70.9', '77.7', '79.0', '73.5', '77.5', '72.1', '75.5',
       '81.7', '74.3', '73.8', '74.1', '69.4', '69.5', '79.4', '78.7',
       '78.4', '78.2', '69.7', '76.0', '79.3', '75.3', '80.1', '73.1',
       '77.1', '72.9', '75.0', '76.3', '73.6', '69.6', '76.7', '78.3',
       '70.2', '72.4', '77.9', '82.3', '72.0', '78.9', '69.8', '54.8',
       '71.4', '77.2', '70.4', '75.8', '81.1', '76.4', '74.2', '75.1',
       '74.7', '76.8', '78.5', '80.0', '84.1', '68.7', '75.2', '81.5',
       '77.0', '72.2', '75.6', '76.2', '70.3', '73.9', '78.1', '79.9',
       '53.4', '71.2', '76.1', '72.8', '74.4', '68.5', '66.6', '67.6',
       '74.6', '77.6', '73.2', '70.8', '73.7', '66.9', '72.6', '82.6',
       '71.5', '78.0', '51.0', '49.0', '70.0', '71.3', '80.2', '74.9',
       '80.7', '79.2', '69.0', '79.1', '68.9', '80.6', '80.4', '73.0',
       '74.0', '75.7', '71.6', '58.8', '71.9', '80.3', '82.0', '79.7',
       '68.2', '74.5', '77.8', '76.6', '71.7', '71.8', '68.4', '56.3',
       '75.4', '70.5', '75.9', '72.3', '67.5', '71.1', '52.7', '47.3',
       '66.8', '67.7', '73.3', '68.6', '72.7', '54.4', '79.6', '81.8',
       '70.7', '69.9', '67.0', '73.4', '67.1', '57.7', '67.4', '69.1',
       '83.5', '66.2', '76.5', '64.0', '68.8', '64.9', '66.7', '83.0',
       '69.2', '79.5', '57.6', '74.8', '65.6', '67.8', '61.9', '62.8',
       '52.0', '48.0', '59.4', '68.1', '65.8', '70.6', '63.2', '51.9',
       '48.1', '58.3', '41.7', '68.0', '71.0', '67.9', '54.0', '69.3',
       '67.2', '62.3', '66.0', '49.4', '58.9', '63.8', '72.5', '67.3',
       '66.4', '45.9', '54.1', '64.4', '82.9', '68.3', '50.8', '49.2',
       '66.5', '53.2', '46.8', '44.6', '47.0', '51.8', '50.0', '50.9',
       '49.7', '47.5', '57.9', '56.9', '55.0', '44.8', '50.3', '41.5',
       '46.9', '48.9', '42.1', '50.4', '61.3', '56.0', '40.3', '47.7',
       '58.5', '52.2', '47.4', '55.3', '53.1', '44.5', '48.8', '45.1',
       '43.8', '54.9', '42.6', '45.8', '56.1', '59.0', '49.8', '46.5',
       '44.1', '49.5', '58.2', '46.4', '55.6', '58.4', '48.5', '57.5',
       '49.6', '53.9', '65.9', '57.8', '51.2', '50.7', '52.6', '62.5',
       '62.1', '56.8', '49.3', '51.3', '48.7', '45.0', '56.5', '54.2',
       '61.5', '52.3', '57.0', '61.6', '57.3', '56.4', '52.9', '47.1',
       '51.7', '63.1', '51.4', '50.1', '62.7', '56.2', '50.5', '55.7',
       '61.0', '59.3', '42.7', '58.6', '63.4', '54.3', '53.6', '46.1',
       '61.8', '52.5', '59.6', '49.9', '53.8', '63.9', '55.9', '58.0',
       '63.0', '52.1', '59.5', '54.6', '55.4', '53.7', '45.7', '57.2',
       '53.3', '55.5', '51.5', '48.4', '55.8', '60.7', '57.1', '58.1',
       '60.1', '60.9', '53.5', '60.6', '64.3', '59.7', '45.5', '56.7',
       '56.6', '61.1', '61.7', '65.5', '62.6', '52.8', '57.4', '60.4',
       '63.6', '62.4', '60.0', '59.9', '59.1', '55.1', '60.8', '60.2',
       '61.2', '60.3', '58.7', '60.5', '64.8', '62.9', '64.7', '59.8',
       '64.6', '62.0', '64.2', '65.3', '63.5', '65.4', '65.1', '81.6',
       '66.3', '65.2', '65.7', '64.5', '65.0'], dtype=object)

In [6]:
df=df[~df['Data_Value'].isin(['*'])]

In [7]:
df=df[pd.notnull(df['Data_Value'])]
df.Data_Value.unique()

array(['13.4', '17.3', '20.0', '18.9', '13.2', '17.1', '13.3', '17.2',
       '19.9', '13.5', '19.3', '18.6', '17.9', '14.0', '18.4', '23.4',
       '23.2', '11.7', '9.3', '12.7', '19.2', '19.6', '12.8', '17.0',
       '18.8', '17.8', '13.7', '21.5', '18.5', '11.9', '14.9', '13.1',
       '21.6', '20.4', '12.3', '10.0', '16.7', '21.4', '19.7', '13.6',
       '16.9', '20.6', '17.6', '14.5', '21.7', '19.1', '12.0', '15.7',
       '11.1', '15.6', '17.4', '13.8', '21.9', '18.7', '12.4', '18.3',
       '15.3', '17.7', '15.9', '20.5', '14.2', '12.9', '12.6', '14.4',
       '19.5', '12.2', '18.2', '17.5', '15.0', '19.8', '16.3', '11.6',
       '20.2', '14.1', '10.7', '22.6', '15.1', '12.1', '21.2', '16.0',
       '16.6', '15.4', '14.8', '20.9', '13.9', '14.3', '16.8', '11.5',
       '22.1', '10.9', '19.4', '20.8', '13.0', '16.4', '15.8', '18.1',
       '19.0', '20.1', '16.1', '20.3', '14.6', '11.8', '23.1', '16.5',
       '10.3', '21.0', '16.2', '23.6', '23.3', '11.3', '8.4', '12.5',
       '24.3', '8.5', '21.1', '21.3', '20.7', '22.7', '11.0', '14.7',
       '10.5', '22.2', '15.2', '10.6', '22.0', '15.5', '18.0', '9.4',
       '10.8', '22.4', '11.2', '24.4', '23.0', '9.6', '23.7', '9.9',
       '23.8', '8.8', '6.6', '26.9', '7.7', '27.3', '9.1', '25.4', '26.3',
       '26.2', '6.2', '26.0', '8.6', '25.7', '24.7', '10.4', '21.8',
       '27.8', '10.2', '6.4', '26.4', '9.5', '8.0', '29.2', '6.5', '24.2',
       '22.3', '7.9', '8.2', '7.4', '9.0', '6.1', '25.8', '11.4', '7.1',
       '22.9', '24.0', '6.3', '29.4', '25.9', '22.8', '5.1', '29.6',
       '5.0', '28.3', '7.8', '23.9', '6.8', '9.7', '25.5', '24.9', '22.5',
       '27.4', '23.5', '27.1', '24.1', '28.2', '25.1', '25.6', '26.1',
       '25.3', '25.0', '24.6', '24.5', '10.1', '25.2', '8.1', '9.8',
       '27.2', '36.2', '35.9', '36.0', '31.6', '36.6', '31.8', '37.9',
       '36.7', '38.3', '35.8', '31.5', '35.1', '33.4', '38.7', '44.3',
       '38.0', '41.0', '27.6', '36.1', '36.3', '48.2', '26.5', '36.9',
       '27.7', '37.6', '34.7', '34.9', '42.2', '37.1', '35.5', '30.0',
       '35.2', '34.8', '28.5', '32.8', '28.8', '35.4', '32.4', '32.9',
       '33.9', '33.7', '37.8', '26.8', '35.7', '42.5', '30.3', '35.3',
       '34.4', '36.8', '29.7', '30.6', '35.0', '38.4', '28.1', '37.0',
       '36.5', '37.2', '38.1', '38.2', '35.6', '39.9', '30.1', '34.6',
       '28.4', '33.8', '29.8', '33.3', '32.0', '32.6', '39.3', '34.2',
       '31.0', '29.5', '37.3', '33.2', '34.0', '42.0', '41.8', '39.4',
       '37.5', '31.7', '32.5', '36.4', '34.3', '38.9', '27.5', '37.7',
       '33.0', '40.7', '34.1', '39.7', '30.9', '42.4', '28.7', '43.7',
       '30.4', '42.8', '34.5', '30.2', '33.5', '29.1', '27.9', '31.2',
       '31.4', '37.4', '39.8', '24.8', '38.5', '28.6', '31.3', '39.1',
       '32.2', '42.3', '41.6', '32.1', '1.8', '2.0', '1.4', '2.6', '2.3',
       '2.1', '2.2', '1.9', '1.7', '45.4', '26.6', '28.0', '2.8', '30.8',
       '29.0', '1.5', '1.6', '38.8', '33.6', '31.1', '26.7', '1.3',
       '38.6', '1.2', '2.5', '31.9', '0.9', '46.0', '41.2', '2.7', '29.9',
       '39.2', '29.3', '32.7', '40.4', '2.9', '28.9', '30.5', '1.1',
       '2.4', '43.0', '3.2', '33.1', '40.1', '27.0', '40.5', '30.7',
       '43.1', '39.5', '32.3', '3.1', '1.0', '43.5', '40.8', '44.4',
       '3.3', '39.0', '40.9', '41.1', '44.0', '40.6', '48.3', '44.9',
       '47.9', '44.2', '48.6', '41.4', '40.0', '40.2', '41.3', '45.6',
       '43.2', '42.9', '39.6', '45.2', '7.2', '0.7', '92.0', '92.1',
       '8.7', '90.3', '93.3', '92.6', '0.5', '91.7', '4.7', '0.6', '94.7',
       '5.9', '93.0', '91.6', '91.2', '0.8', '90.7', '91.5', '7.6',
       '93.1', '7.3', '6.7', '92.7', '6.0', '90.9', '91.9', '7.0', '92.9',
       '91.4', '5.5', '93.7', '0.4', '88.6', '6.9', '93.8', '5.6', '93.5',
       '5.7', '91.0', '93.2', '8.9', '90.2', '92.8', '92.5', '89.7',
       '92.2', '89.8', '5.8', '93.6', '89.5', '88.4', '88.8', '91.1',
       '89.9', '4.2', '90.5', '90.6', '4.3', '94.0', '8.3', '90.0',
       '90.4', '92.4', '7.5', '88.5', '91.8', '90.1', '5.3', '87.5',
       '0.2', '87.4', '87.3', '4.4', '4.8', '93.4', '89.4', '88.9', '9.2',
       '89.0', '91.3', '92.3', '89.6', '87.9', '0.1', '84.8', '86.7',
       '89.3', '90.8', '88.1', '89.1', '86.9', '86.0', '86.2', '87.0',
       '88.7', '87.7', '88.3', '87.6', '86.6', '85.7', '88.2', '88.0',
       '86.3', '89.2', '86.1', '85.4', '87.8', '86.4', '85.5', '0.3',
       '85.9', '85.6', '86.8', '5.2', '83.1', '87.1', '85.1', '87.2',
       '3.9', '84.0', '83.7', '84.5', '86.5', '3.7', '82.4', '85.0',
       '84.4', '81.3', '83.8', '4.6', '3.5', '83.6', '85.3', '85.2',
       '77.4', '84.2', '3.8', '81.0', '82.2', '84.9', '85.8', '83.4',
       '84.7', '83.2', '82.1', '82.7', '83.3', '80.5', '4.0', '4.9',
       '84.3', '83.9', '82.8', '81.2', '3.6', '81.9', '79.8', '84.6',
       '80.9', '82.5', '3.0', '3.4', '81.4', '78.6', '95.7', '94.3',
       '93.9', '94.5', '94.6', '95.0', '94.2', '5.4', '94.4', '4.5',
       '94.8', '47.8', '47.2', '44.7', '43.4', '51.1', '50.6', '54.5',
       '43.9', '46.6', '46.2', '55.2', '43.3', '43.6', '47.6', '62.2',
       '4.1', '46.3', '59.2', '50.2', '41.9', '49.1', '51.6', '52.4',
       '53.0', '54.7', '46.7', '45.3', '76.9', '77.3', '70.1', '80.8',
       '78.8', '70.9', '77.7', '79.0', '73.5', '77.5', '72.1', '75.5',
       '81.7', '74.3', '73.8', '74.1', '69.4', '69.5', '79.4', '78.7',
       '78.4', '78.2', '69.7', '76.0', '79.3', '75.3', '80.1', '73.1',
       '77.1', '72.9', '75.0', '76.3', '73.6', '69.6', '76.7', '78.3',
       '70.2', '72.4', '77.9', '82.3', '72.0', '78.9', '69.8', '54.8',
       '71.4', '77.2', '70.4', '75.8', '81.1', '76.4', '74.2', '75.1',
       '74.7', '76.8', '78.5', '80.0', '84.1', '68.7', '75.2', '81.5',
       '77.0', '72.2', '75.6', '76.2', '70.3', '73.9', '78.1', '79.9',
       '53.4', '71.2', '76.1', '72.8', '74.4', '68.5', '66.6', '67.6',
       '74.6', '77.6', '73.2', '70.8', '73.7', '66.9', '72.6', '82.6',
       '71.5', '78.0', '51.0', '49.0', '70.0', '71.3', '80.2', '74.9',
       '80.7', '79.2', '69.0', '79.1', '68.9', '80.6', '80.4', '73.0',
       '74.0', '75.7', '71.6', '58.8', '71.9', '80.3', '82.0', '79.7',
       '68.2', '74.5', '77.8', '76.6', '71.7', '71.8', '68.4', '56.3',
       '75.4', '70.5', '75.9', '72.3', '67.5', '71.1', '52.7', '47.3',
       '66.8', '67.7', '73.3', '68.6', '72.7', '54.4', '79.6', '81.8',
       '70.7', '69.9', '67.0', '73.4', '67.1', '57.7', '67.4', '69.1',
       '83.5', '66.2', '76.5', '64.0', '68.8', '64.9', '66.7', '83.0',
       '69.2', '79.5', '57.6', '74.8', '65.6', '67.8', '61.9', '62.8',
       '52.0', '48.0', '59.4', '68.1', '65.8', '70.6', '63.2', '51.9',
       '48.1', '58.3', '41.7', '68.0', '71.0', '67.9', '54.0', '69.3',
       '67.2', '62.3', '66.0', '49.4', '58.9', '63.8', '72.5', '67.3',
       '66.4', '45.9', '54.1', '64.4', '82.9', '68.3', '50.8', '49.2',
       '66.5', '53.2', '46.8', '44.6', '47.0', '51.8', '50.0', '50.9',
       '49.7', '47.5', '57.9', '56.9', '55.0', '44.8', '50.3', '41.5',
       '46.9', '48.9', '42.1', '50.4', '61.3', '56.0', '40.3', '47.7',
       '58.5', '52.2', '47.4', '55.3', '53.1', '44.5', '48.8', '45.1',
       '43.8', '54.9', '42.6', '45.8', '56.1', '59.0', '49.8', '46.5',
       '44.1', '49.5', '58.2', '46.4', '55.6', '58.4', '48.5', '57.5',
       '49.6', '53.9', '65.9', '57.8', '51.2', '50.7', '52.6', '62.5',
       '62.1', '56.8', '49.3', '51.3', '48.7', '45.0', '56.5', '54.2',
       '61.5', '52.3', '57.0', '61.6', '57.3', '56.4', '52.9', '47.1',
       '51.7', '63.1', '51.4', '50.1', '62.7', '56.2', '50.5', '55.7',
       '61.0', '59.3', '42.7', '58.6', '63.4', '54.3', '53.6', '46.1',
       '61.8', '52.5', '59.6', '49.9', '53.8', '63.9', '55.9', '58.0',
       '63.0', '52.1', '59.5', '54.6', '55.4', '53.7', '45.7', '57.2',
       '53.3', '55.5', '51.5', '48.4', '55.8', '60.7', '57.1', '58.1',
       '60.1', '60.9', '53.5', '60.6', '64.3', '59.7', '45.5', '56.7',
       '56.6', '61.1', '61.7', '65.5', '62.6', '52.8', '57.4', '60.4',
       '63.6', '62.4', '60.0', '59.9', '59.1', '55.1', '60.8', '60.2',
       '61.2', '60.3', '58.7', '60.5', '64.8', '62.9', '64.7', '59.8',
       '64.6', '62.0', '64.2', '65.3', '63.5', '65.4', '65.1', '81.6',
       '66.3', '65.2', '65.7', '64.5', '65.0'], dtype=object)

In [8]:
df['Data_Value']=df.Data_Value.astype('float64')

In [9]:
# calculate diabetes value & add to df
df['Diabetes_Value']= df['Sample_Size']*df['Data_Value']
df.head()

,ID,Year,LocationAbbr,Topic,Response,Data_Value_Type,Data_Value,Data_Value_Footnote_Symbol,Data_Value_Footnote,Low_Confidence_Limit,High_Confidence_Limit,Sample_Size,Stratification,StratificationType,IndicatorId,LocationOrder,ParentStateDisplayOrder,Diabetes_Value
0,881138.0,2003.0,US,Age,18-24 years,Crude Prevalence,13.4,**,Median value reported with no confidence inter...,NaN,NaN,54.0,Overall,Overall,AGE,1.0,1.0,723.6
1,881139.0,2003.0,US,Age,25-34 years,Crude Prevalence,17.3,**,Median value reported with no confidence inter...,NaN,NaN,54.0,Overall,Overall,AGE,1.0,1.0,934.2
2,881140.0,2003.0,US,Age,35-44 years,Crude Prevalence,20.0,**,Median value reported with no confidence inter...,NaN,NaN,54.0,Overall,Overall,AGE,1.0,1.0,1080.0
3,881141.0,2003.0,US,Age,45-54 years,Crude Prevalence,18.9,**,Median value reported with no confidence inter...,NaN,NaN,54.0,Overall,Overall,AGE,1.0,1.0,1020.6
4,881142.0,2003.0,US,Age,55-64 years,Crude Prevalence,13.2,**,Median value reported with no confidence inter...,NaN,NaN,54.0,Overall,Overall,AGE,1.0,1.0,712.8

In [10]:
# set index to ID
df.set_index('ID')

,Year,LocationAbbr,Topic,Response,Data_Value_Type,Data_Value,Data_Value_Footnote_Symbol,Data_Value_Footnote,Low_Confidence_Limit,High_Confidence_Limit,Sample_Size,Stratification,StratificationType,IndicatorId,LocationOrder,ParentStateDisplayOrder,Diabetes_Value
ID,,,,,,,,,,,,,,,,,
881138.0,2003.0,US,Age,18-24 years,Crude Prevalence,13.4,**,Median value reported with no confidence inter...,NaN,NaN,54.0,Overall,Overall,AGE,1.0,1.0,723.6
881139.0,2003.0,US,Age,25-34 years,Crude Prevalence,17.3,**,Median value reported with no confidence inter...,NaN,NaN,54.0,Overall,Overall,AGE,1.0,1.0,934.2
881140.0,2003.0,US,Age,35-44 years,Crude Prevalence,20.0,**,Median value reported with no confidence inter...,NaN,NaN,54.0,Overall,Overall,AGE,1.0,1.0,1080.0
881141.0,2003.0,US,Age,45-54 years,Crude Prevalence,18.9,**,Median value reported with no confidence inter...,NaN,NaN,54.0,Overall,Overall,AGE,1.0,1.0,1020.6
881142.0,2003.0,US,Age,55-64 years,Crude Prevalence,13.2,**,Median value reported with no confidence inter...,NaN,NaN,54.0,Overall,Overall,AGE,1.0,1.0,712.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1137497.0,2001.0,GU,High Blood Pressure,No,Crude Prevalence,75.5,NaN,NaN,72.1,78.9,678.0,Overall,Overall,_RFHYPE3,56.0,56.0,51189.0
1200198.0,2001.0,PR,High Blood Pressure,Yes,Crude Prevalence,26.4,NaN,NaN,24.7,28.1,1360.0,Overall,Overall,_RFHYPE3,60.0,60.0,35904.0
1200199.0,2001.0,PR,High Blood Pressure,No,Crude Prevalence,73.6,NaN,NaN,71.9,75.3,2869.0,Overall,Overall,_RFHYPE3,60.0,60.0,211158.4
1218319.0,2001.0,VI,High Blood Pressure,Yes,Crude Prevalence,26.5,NaN,NaN,24.2,28.8,619.0,Overall,Overall,_RFHYPE3,62.0,62.0,16403.5
1218320.0,2001.0,VI,High Blood Pressure,No,Crude Prevalence,73.5,NaN,NaN,71.2,75.8,1640.0,Overall,Overall,_RFHYPE3,62.0,62.0,120540.0

In [11]:
# reshape table
# clean_df =  df.pivot(columns='Topic',values='Response')
# clean_df  -- found an issue with the data after trying this block of code

In [12]:
df.nunique()

ID                            33179
Year                             20
LocationAbbr                     56
Topic                             9
Response                         30
Data_Value_Type                   1
Data_Value                      944
Data_Value_Footnote_Symbol        1
Data_Value_Footnote               1
Low_Confidence_Limit            940
High_Confidence_Limit           957
Sample_Size                    6633
Stratification                    1
StratificationType                1
IndicatorId                      17
LocationOrder                    56
ParentStateDisplayOrder          56
Diabetes_Value                29901
dtype: int64

In [13]:
df.shape

(34523, 18)

In [15]:
# drop US
df=df[~df['LocationAbbr'].isin(['US'])]